name: Bump Casks
on:
  schedule:
    - cron: '0 4,16 * * *'
  workflow_dispatch:
jobs:
  bump-aonsoku-cask-versions:
    steps:
      - uses: friesi23/action-homebrew-bump-cask@v2
        with:
          token: ${{secrets.BUMP_CASK_TOKEN}}
          tap: 9numbernine9/homebrew
          cask: aonsoku
          livecheck: true
